[theme]

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
primaryColor="#EFBB0F"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#EFEFE9"
textColor="#262730"

# Streamlit version: 1.20.0